* Main operations and operator
Main operations are:
1. Creating and modifying patterns
   1. Set duration pattern (and optionally also beat pattern) of a Beat instance
   2. Set beat pattern of a Beat instance
   3. Set beat pattern of a subpattern of a Beat instance
2. Playing Chucks in patterns

Draft for operators:


set duration pattern of a Beat instance, and start playing:

: <pattern or number> %% \symbol;

set duration pattern + beat pattern of a Beat instance, and start playing:

: <pattern or number> %%.beatpattern \symbol;

Note: beatpattern can be a symbol, x denoting active beats, anything else non-active beats.

Set beat pattern of main beat of Beat \beat:
: "xoxoxxx" %% \beat
	// or:
: 'xoxoxxx' %% \beat

Set beat pattern of subbeat pattern \bass of Beat \beat:
: "xxxoo" %%.bass \beat
	// or:
: 'xxxoo' %%.bass \beat

Play chuck in Beat instance

Play chuck in Beat instance with own beat pattern (create beat if it does not already exist.)
Beat filter subbeat name defaults to 'default'.
: <chuck or symbol> %%.beatpattern \beat;

Play chuck in subbeat name of Beat instance.
Subbeat path (can have any subbeat depth) is given by separating subbeat names by =_=:

: <chuck or symbol> %% \subbeat_beat;
* Chaining %% expressions for brevity

DRAFT!

Possibilities:
** A: chuck -> beat

chuckname %% beatname

chuckname %% pattern %% beatname

function %% chuckname %% pattern %% beatname
** B: beat -> chuck

beatname %% chuckname

pattern %% beatname %% chuckname

pattern %% beatname %% function %% chuckname

* Defaults

: <chuck or symbol> %% \beatname

If Beat named \beatname does not exist, it is created using a default global duration as beat duration.


* Possible extension: Subpatterns of different tempi

Set some subpatterns to operate at a tempo relative to the main tempo of the pattern?

They should start relative to the first beat of the main pattern ...

Nested subpatterns possible?
