* Preamble
:PROPERTIES:
:DATE:     <2014-05-06 Tue 21:42>
:END:

The initial idea for tiny-sc was given by Mini-Audicle in ChucK.  http://audicle.cs.princeton.edu/mini/.  The Mini-Audicle includes a window for the Virtual Machine of ChucK, which displays running processes (shreds).  Through this GUI the user can at any point view which processes are running and stop any one of them.  Thus the idea arose to emulate such a functionality in SuperCollider.  This was implemented here with a new class ProcessRegistry in conjunction with some ancilliary methods.  From then on, the tiny-sc project developed without plan, as a series of spontaneous experiments with alternative approaches to common tasks in SuperColllider.

* Some objectives
:PROPERTIES:
:DATE:     <2014-05-05 Mon 11:25>
:END:

(To be rewritten...):

1. Track the state of the Server and of Synths.

2. Simplify the definition of SynthDef Functions with UGen generation shortcuts

3. Manage the loading of lists of buffers, and making these available to synths

4. Simplify the linking of audio inputs and outputs between synths through busses.

   - Automatically allocate and assign audio busses to inputs and outputs.

   - Automatically maintain correct order of nodes in the scsynth graph.

   - Restart entire synth graph on demand

5. Simplify and unify the mechanism for listening to control events broadcasts, by extending the mechanism of AbstractResponderFunc (eg. OSCFunc, MIDIFunc) to Views and Patterns.

* Tracking Server/Synth state



* UGen shortcuts

* Buffer handling

* Audio I/O linking

* Playing patterns
